# Generated by Django 5.0.4 on 2025-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
