# Generated by Django 5.0.4 on 2025-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agenda_lembrete_enviado_alter_agenda_terapeuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='lembrete_enviado',
        ),
        migrations.AddField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
