# Generated by Django 5.0.4 on 2025-03-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_agenda_lembrete_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
