# Generated by Django 5.0.4 on 2025-04-10 22:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agenda_status_lembrete'),
        ('cadastro_paciente', '0019_adicionar_celular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['date'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario_lembrete',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Horário em que o lembrete será enviado no dia anterior à consulta', verbose_name='Horário do Lembrete'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='confirmada',
            field=models.BooleanField(default=False, verbose_name='Consulta Confirmada'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateTimeField(verbose_name='Data e Hora da Consulta'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_paciente.cadastropaciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(blank=True, choices=[('Não enviado', 'Não enviado'), ('Aguardando envio', 'Aguardando envio'), ('Enviado', 'Enviado'), ('Falha', 'Falha no envio')], default='Não enviado', max_length=255, null=True, verbose_name='Status do Lembrete'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terapeuta'),
        ),
    ]
