# Generated by Django 5.0.4 on 2025-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agenda_options_agenda_horario_lembrete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario_lembrete',
            field=models.TimeField(help_text='Horário em que o lembrete será enviado no dia anterior à consulta', verbose_name='Horário do Lembrete'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(choices=[('Não enviado', 'Não enviado'), ('Aguardando envio', 'Aguardando envio'), ('Enviado', 'Enviado'), ('Falha', 'Falha no envio')], default='Não enviado', max_length=50, verbose_name='Status do Lembrete'),
        ),
    ]
