# Generated by Django 5.0.4 on 2025-04-25 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_agenda_horario_lembrete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cadastropaciente', verbose_name='Paciente'),
        ),
    ]
