# Generated by Django 5.0.4 on 2025-04-26 00:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_cadastropaciente_alter_agenda_paciente'),
        ('cadastro_paciente', '0019_adicionar_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_paciente.cadastropaciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, verbose_name='Valor da Consulta (R$)'),
        ),
        migrations.DeleteModel(
            name='CadastroPaciente',
        ),
    ]
