# Generated by Django 5.0.4 on 2025-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_agenda_paciente_agenda_valor_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(choices=[('Não enviado', 'Não enviado'), ('Aguardando envio', 'Aguardando envio'), ('Enviado', 'Enviado'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Falha', 'Falha no envio')], default='Não enviado', max_length=50, verbose_name='Status do Lembrete'),
        ),
    ]
