# Generated by Django 5.0.4 on 2025-05-12 02:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_agenda_status_lembrete'),
        ('cadastro_paciente', '0019_adicionar_celular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario_lembrete',
            field=models.TimeField(verbose_name='Horário do Lembrete'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_paciente.cadastropaciente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(choices=[('Não enviado', 'Não enviado'), ('Aguardando envio', 'Aguardando envio'), ('Enviado', 'Enviado'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Falha', 'Falha no envio')], default='Não enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10),
        ),
    ]
