# Generated by Django 5.1.2 on 2025-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_agenda_options_alter_agenda_confirmada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horario_lembrete',
        ),
    ]
