# Generated by Django 5.1.2 on 2025-05-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_remove_agenda_horario_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horario_lembrete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário do Lembrete'),
        ),
    ]
