# Generated by Django 5.1.2 on 2025-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agenda_horario_lembrete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['date'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario_lembrete',
            field=models.TimeField(default='16:00', verbose_name='Horário do Lembrete'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status_lembrete',
            field=models.CharField(choices=[('Não enviado', 'Não enviado'), ('Aguardando envio', 'Aguardando envio'), ('Enviado', 'Enviado'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Falha', 'Falha no envio'), ('Confirmada pelo paciente', 'Confirmada pelo paciente')], default='Não enviado', max_length=50),
        ),
    ]
