# Generated by Django 5.1.2 on 2024-11-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilpaciente',
            old_name='codigoAcesso',
            new_name='codigo_acesso',
        ),
    ]
