# Generated by Django 5.1.2 on 2025-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_pacientes', '0003_perfilpaciente_terapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
