# Generated by Django 5.1.2 on 2025-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_pacientes', '0004_perfilpaciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='email',
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='codigo_acesso',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
