# Generated by Django 5.1.2 on 2025-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_pacientes', '0005_remove_perfilpaciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpaciente',
            name='codigo_acesso',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
