# Generated by Django 5.0.4 on 2024-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0009_alter_cadastropaciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
    ]
