# Generated by Django 5.0.4 on 2024-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0011_alter_cadastropaciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável'), ('outro', 'Outro')], max_length=50, null=True),
        ),
    ]
