# Generated by Django 5.1.2 on 2024-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0012_alter_cadastropaciente_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='data_nascimento',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
