# Generated by Django 5.1.2 on 2024-11-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0015_alter_cadastropaciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastropaciente',
            name='sexo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
