# Generated by Django 5.1.2 on 2024-11-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0013_alter_cadastropaciente_sexo'),
        ('cadastro_paciente', '0016_alter_cadastropaciente_data_nascimento_and_more'),
    ]

    operations = [
    ]
